[project]
name = "midterm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "peft>=0.14.0",
    "torch>=2.6.0",
    "transformers>=4.49.0",
]
